{{- if eq .Values.runtime "kn" -}}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  #namespace: {{ .Values.service.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}"
        ports:
          - containerPort: {{ .Values.service.port }}
      {{- with .Values.service.env }}
        env:
         {{- toYaml . | nindent 10 }}
      {{- end }}
{{- with .Values.knative.traffic }}
  traffic:
    {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
