{{- if eq .Values.runtime "cn" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pksdemo.fullname" . }}
  labels:
{{ include "pksdemo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pksdemo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- if eq .Values.deployStrategy "bg" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pksdemo.fullname" . }}-preview
  labels:
{{ include "pksdemo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pksdemo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
---
{{- if eq .Values.deployStrategy "canary" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pksdemo.fullname" . }}-preview
  labels:
{{ include "pksdemo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "pksdemo.name" . }}-preview
{{- end }}
{{- end }}
