{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pksdemo.serviceAccountName" . }}
  labels:
{{ include "pksdemo.labels" . | indent 4 }}
{{- end -}}
