apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  #
  #
  #   source-provider <--[src]-- image-builder <--[img]--- deployer
  #     GitRepository               Image                    App
  #
  #
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - resource: source-provider
          name: source

 #  - name: deployer
  #    templateRef:
  #      kind: ClusterTemplate
  #      name: app-deploy
  #    images:
  #      - resource: image-builder
  #        name: image

    - name: updater
      templateRef:
        kind: ClusterTemplate
        name: update-image-tag
      images:
        - resource: image-builder
          name: image
