#! #@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pksdemo
  labels:
    app.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello-world
spec:
  params:
    - name: env
      value: dev
  source:
    git:
      url: ssh://git@gitlab.haas-495.pez.vmware.com/jeffrey/pksdemo
      ref:
        branch: master

